//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MUL.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_MULTYPE                     129
#define IDR_LADDER                      130
#define IDC_LD                          133
#define IDC_LDI                         134
#define IDC_OR                          135
#define IDC_ORI                         136
#define IDD_WORKARESET                  136
#define IDC_OUT                         137
#define IDC_ADDITION                    138
#define IDR_DRAWTYPE                    144
#define IDB_BITMAP1                     152
#define IDB_BITMAP2                     153
#define IDR_ITEMMENU                    154
#define IDR_ACCELERATOR1                156
#define IDB_BITMAP3                     158
#define IDD_SYNTAX                      159
#define IDD_POINTSET                    160
#define IDD_DLG_COMMUNICATION           161
#define IDD_DIG_COMPILE                 162
#define IDD_DLG_OPENCOM                 165
#define IDD_DLG_SETTINGCOM              166
#define IDD_DIALOG1                     167
#define IDC_WORKARE_WIDTH               1000
#define IDC_WORKARE_HIGH                1001
#define IDC_BTN_PLCTOTXT                1001
#define IDC_PAGEHIGH                    1002
#define IDC_BTN_OPEN_DOWNLOADFILE       1002
#define IDC_COMPILE                     1003
#define IDC_PAGEWIDTH                   1003
#define IDC_BTN_COMPILE                 1003
#define IDC_ADDR                        1004
#define IDC_NAME                        1005
#define IDC_BTN_DOWNLOAD                1005
#define IDC_NOTE                        1006
#define IDC_EDIT_SHOWLOG                1006
#define IDC_CAPTION                     1007
#define IDC_BTN_OPEN_BINFILE            1007
#define IDC_CHK_DELETEFILE              1008
#define IDC_BTN_UPLOADTO                1009
#define IDC_BTN_CONVERT                 1010
#define IDC_BTN_UPLOAD                  1010
#define IDC_BTN_DECOMPILE               1010
#define IDC_SOURFILENAME                1011
#define IDC_DECOMPILE                   1011
#define IDC_BTN_SAVE_TXTFILE            1012
#define IDC_COMBO_DOWNCOM               1013
#define IDC_SOURFILENAME2               1013
#define IDC_BTN_OPENCOM                 1014
#define IDC_COMBO_UPCOM                 1015
#define IDC_CHK_COM1                    1016
#define IDC_CHK_COM2                    1017
#define IDC_CHK_COM3                    1018
#define IDC_BTN_SETTINGCOM1             1019
#define IDC_BTN_SETTINGCOM2             1020
#define IDC_COMBO_BAUD                  1020
#define IDC_BTN_SETTINGCOM3             1021
#define IDC_BTN_SETTINGCOM4             1022
#define IDC_BTN_SETTINGCOM5             1023
#define IDC_EDIT_MASTERSTATION          1024
#define IDC_EDIT_SUBSTATION             1026
#define IDC_BUTTON1                     1029
#define IDC_BTN_PLC                     1029
#define IDC_COMBO_DATABIT               1030
#define IDC_BUTTON2                     1030
#define IDC_BTN_BIN                     1030
#define IDC_COMBO_STOPBIT               1031
#define IDC_EDIT1                       1031
#define IDC_COMBO_CHECKSUM              1032
#define IDC_EDIT2                       1032
#define IDC_EDIT3                       1033
#define IDC_DESTFILENAME                1036
#define IDC_BTN_DECOMPIL                1037
#define IDC_RADIO1                      1038
#define IDC_RADIO2                      1039
#define IDC_RADIO3                      1040
#define IDC_RADIO4                      1041
#define IDC_RADIO5                      1042
#define IDC_RADIO6                      1043
#define IDC_CHECK1                      1044
#define IDC_CHECK2                      1045
#define IDC_CHK_COM4                    1818
#define ID_DRAW_FREE                    32771
#define ID_DRAW_LD                      32772
#define ID_DRAW_LDI                     32773
#define ID_DRAW_OR                      32774
#define ID_DRAW_ORI                     32775
#define ID_DRAW_LINE                    32776
#define ID_DRAW_OUT                     32777
#define ID_DRAW_ADDITION                32778
#define ID_DRAW_ERASE                   32779
#define ID_VIEW_LADDER                  32784
#define ID_VIEW_INSTRU                  32785
#define ID_VIEW_ADDRESS                 32786
#define ID_OPTION_WORKARE               32787
#define ID_OPTION_FONT                  32788
#define ID_OPTION_SETADDR               32791
#define ID_COMPILE_LADD                 32793
#define ID_COMPILE_LAD                  32794
#define ID_SELECT_SET                   32795
#define ID_SELECT_RST                   32796
#define ID_SELECT_S                     32797
#define ID_SELECT_R                     32798
#define ID_SELECT_MC                    32799
#define ID_SELECT_MCR                   32800
#define ID_SELECT_K                     32801
#define ID_SELECT_F                     32802
#define ID_SELECT_CJP                   32803
#define ID_SELECT_EJP                   32804
#define ID_SELECT_PLS                   32805
#define ID_SELECT_END                   32806
#define ID_COMPILE_INSTR                32807
#define ID_COMMUN_DOWNLOAD              32812
#define ID_COMMUN_UPLOAD                32813
#define ID_32814                        32814
#define ID_32815                        32815
#define ID_INDICATOR_MOUSE              59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
